-- ═══════════════════════════════════════════════════════════
--  SERGEEV AGENTS PLATFORM — Supabase Schema
--  Run this in Supabase SQL Editor (one time)
-- ═══════════════════════════════════════════════════════════

-- ─── 1. Bot Pool (pre-created Telegram bots) ───
CREATE TABLE IF NOT EXISTS bot_pool (
  id            BIGSERIAL PRIMARY KEY,
  bot_username  TEXT NOT NULL UNIQUE,          -- @sergeev_agents_001_bot
  bot_token     TEXT NOT NULL UNIQUE,          -- from BotFather
  status        TEXT NOT NULL DEFAULT 'available'  -- available | assigned | suspended
                CHECK (status IN ('available', 'assigned', 'suspended')),
  assigned_to_client_id BIGINT,               -- FK filled on assignment
  created_at    TIMESTAMPTZ DEFAULT now(),
  assigned_at   TIMESTAMPTZ
);

CREATE INDEX idx_bot_pool_status ON bot_pool(status);
CREATE INDEX idx_bot_pool_token ON bot_pool(bot_token);
CREATE INDEX idx_bot_pool_client ON bot_pool(assigned_to_client_id);

-- ─── 2. Clients ───
CREATE TABLE IF NOT EXISTS clients (
  id              BIGSERIAL PRIMARY KEY,
  business_name   TEXT NOT NULL,
  industry        TEXT,                        -- "автомасла", "барбершоп", "юрфирма"
  contacts        JSONB DEFAULT '{}',          -- {phone, address, website, hours}
  system_prompt   TEXT NOT NULL,               -- generated by Dmitry
  catalog_data    JSONB,                       -- products/services
  business_rules  JSONB,                       -- custom rules
  bot_id          BIGINT REFERENCES bot_pool(id),
  plan            TEXT DEFAULT 'trial'
                  CHECK (plan IN ('trial', 'starter', 'business', 'premium', 'enterprise')),
  status          TEXT DEFAULT 'trial'
                  CHECK (status IN ('trial', 'active', 'suspended', 'churned')),
  onboarded_at    TIMESTAMPTZ DEFAULT now(),
  manager_telegram_id TEXT,                    -- for future: client's manager alerts
  metadata        JSONB DEFAULT '{}'           -- any extra data
);

CREATE INDEX idx_clients_status ON clients(status);
CREATE INDEX idx_clients_plan ON clients(plan);

-- ─── 3. Plans (reference table) ───
CREATE TABLE IF NOT EXISTS plans (
  id              TEXT PRIMARY KEY,            -- starter, business, premium, enterprise
  name_ru         TEXT NOT NULL,
  price_rub       INTEGER NOT NULL,
  requests_month  INTEGER NOT NULL,
  channels        TEXT[] DEFAULT '{"telegram"}',
  features        JSONB DEFAULT '{}',
  is_active       BOOLEAN DEFAULT true
);

INSERT INTO plans (id, name_ru, price_rub, requests_month, channels, features) VALUES
  ('starter',    'Стартовый',     60000,   3000,  '{"telegram"}',                     '{"agents": 1, "catalog_items": 50}'),
  ('business',   'Бизнес',        120000,  10000, '{"telegram", "widget"}',            '{"agents": 1, "catalog_items": 500, "crm_alerts": true}'),
  ('premium',    'Премиум',       300000,  30000, '{"telegram", "widget", "whatsapp"}','{"agents": 2, "analytics": true, "priority": true}'),
  ('enterprise', 'Корпоративный', 0,       999999,'{"telegram", "widget", "whatsapp", "email"}', '{"agents": "unlimited", "dedicated_manager": true}')
ON CONFLICT (id) DO NOTHING;

-- ─── 4. Usage (monthly counters) ───
CREATE TABLE IF NOT EXISTS usage (
  id                  BIGSERIAL PRIMARY KEY,
  client_id           BIGINT NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
  month               TEXT NOT NULL,           -- "2026-04"
  requests_used       INTEGER DEFAULT 0,
  requests_limit      INTEGER NOT NULL,
  is_trial            BOOLEAN DEFAULT false,
  trial_requests_left INTEGER,
  created_at          TIMESTAMPTZ DEFAULT now(),
  UNIQUE(client_id, month)
);

CREATE INDEX idx_usage_client_month ON usage(client_id, month);

-- ─── 5. Conversations (all bot messages) ───
CREATE TABLE IF NOT EXISTS conversations (
  id                    BIGSERIAL PRIMARY KEY,
  client_id             BIGINT NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
  end_user_telegram_id  TEXT NOT NULL,
  end_user_name         TEXT,
  role                  TEXT NOT NULL CHECK (role IN ('user', 'assistant')),
  content               TEXT NOT NULL,
  tokens_used           INTEGER DEFAULT 0,
  created_at            TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX idx_conv_client_user ON conversations(client_id, end_user_telegram_id);
CREATE INDEX idx_conv_created ON conversations(created_at DESC);

-- Partition by month for performance at scale (optional, enable later)
-- CREATE TABLE conversations_2026_04 PARTITION OF conversations
--   FOR VALUES FROM ('2026-04-01') TO ('2026-05-01');

-- ─── 6. Client Users (end-users of client bots) ───
CREATE TABLE IF NOT EXISTS client_users (
  id              BIGSERIAL PRIMARY KEY,
  client_id       BIGINT NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
  telegram_id     TEXT NOT NULL,
  name            TEXT,
  context_summary TEXT,                        -- AI-generated summary of this user
  first_seen      TIMESTAMPTZ DEFAULT now(),
  last_seen       TIMESTAMPTZ DEFAULT now(),
  metadata        JSONB DEFAULT '{}',
  UNIQUE(client_id, telegram_id)
);

CREATE INDEX idx_client_users_lookup ON client_users(client_id, telegram_id);

-- ─── 7. Billing ───
CREATE TABLE IF NOT EXISTS billing (
  id              BIGSERIAL PRIMARY KEY,
  client_id       BIGINT NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
  plan            TEXT NOT NULL,
  amount_rub      INTEGER NOT NULL,
  period_start    DATE NOT NULL,
  period_end      DATE NOT NULL,
  status          TEXT DEFAULT 'pending'
                  CHECK (status IN ('pending', 'paid', 'overdue', 'cancelled')),
  paid_at         TIMESTAMPTZ,
  invoice_url     TEXT,
  created_at      TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX idx_billing_client ON billing(client_id);
CREATE INDEX idx_billing_status ON billing(status);

-- ─── 8. Onboarding Sessions (Dmitry's conversations) ───
CREATE TABLE IF NOT EXISTS onboarding_sessions (
  id                    BIGSERIAL PRIMARY KEY,
  prospect_telegram_id  TEXT NOT NULL,
  prospect_name         TEXT,
  stage                 TEXT DEFAULT 'intro'
                        CHECK (stage IN ('intro', 'questions', 'prompt_gen', 'bot_assign', 'testing', 'complete', 'abandoned')),
  collected_data        JSONB DEFAULT '{}',
  generated_prompt      TEXT,
  assigned_bot_id       BIGINT REFERENCES bot_pool(id),
  created_at            TIMESTAMPTZ DEFAULT now(),
  completed_at          TIMESTAMPTZ,
  metadata              JSONB DEFAULT '{}'
);

CREATE INDEX idx_onboarding_prospect ON onboarding_sessions(prospect_telegram_id);
CREATE INDEX idx_onboarding_stage ON onboarding_sessions(stage);

-- ─── 9. Error Log (monitoring) ───
CREATE TABLE IF NOT EXISTS error_log (
  id              BIGSERIAL PRIMARY KEY,
  client_id       BIGINT,
  bot_token_last4 TEXT,
  error_type      TEXT NOT NULL,               -- claude_error, telegram_error, db_error
  error_message   TEXT NOT NULL,
  context         JSONB DEFAULT '{}',
  created_at      TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX idx_errors_type ON error_log(error_type);
CREATE INDEX idx_errors_created ON error_log(created_at DESC);

-- ─── 10. Useful views ───

-- Active clients with their bot info
CREATE OR REPLACE VIEW v_active_clients AS
SELECT
  c.id,
  c.business_name,
  c.industry,
  c.plan,
  c.status,
  b.bot_username,
  c.onboarded_at,
  COALESCE(u.requests_used, 0) as current_month_requests
FROM clients c
LEFT JOIN bot_pool b ON b.id = c.bot_id
LEFT JOIN usage u ON u.client_id = c.id
  AND u.month = to_char(now(), 'YYYY-MM')
WHERE c.status IN ('trial', 'active')
ORDER BY c.onboarded_at DESC;

-- Daily stats
CREATE OR REPLACE VIEW v_daily_stats AS
SELECT
  date_trunc('day', created_at) AS day,
  COUNT(*) FILTER (WHERE role = 'user') AS user_messages,
  COUNT(*) FILTER (WHERE role = 'assistant') AS bot_messages,
  COUNT(DISTINCT end_user_telegram_id) AS unique_users,
  COUNT(DISTINCT client_id) AS active_bots,
  SUM(tokens_used) AS total_tokens
FROM conversations
WHERE created_at > now() - interval '30 days'
GROUP BY 1
ORDER BY 1 DESC;

-- ─── RLS (Row Level Security) ───
-- For now, disable RLS since master-bot uses service key
-- Enable when adding client dashboard access

-- GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA public TO anon;
-- GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anon;
